### ISSUE TITLE
Potential collision excluded in SRDF 

### ISSUE THREAD

**Issue by yck011522** [gramaziokohler/rfl_description#3]
https://github.com/gramaziokohler/rfl_description/blob/0721d7bca5ae4540fbd474aa2f1afc2e76e48360/rfl_description/urdf/rfl.srdf#L198

See this issue:
https://github.com/gramaziokohler/integral_timber_joints/issues/35

I suggest line 198 be removed. 
This exception between `baselink` and `link2` is only there for `robot11`. Other three robots don't have this line. And yes, of course I discovered this problem because I already crashed the robot.

**Comment by yijiangh** [comment]
Fixed at https://github.com/yijiangh/rfl_description/commit/1b5ed4135f73ff2ae3a3ef5f5c1a578214fa45e5

**Comment by matteo-pacher** [comment]
Thank you Victor for pointing that out!
I pushed https://github.com/gramaziokohler/rfl_description/commit/7a0fd0bf9390f2a6e1999df4671a8847bc6b039c to fix this.
